default:
	$(CC) uppg1.c -o uppg1 -Wall -O0 -g
	$(CC) uppg2.c -o uppg2 -Wall -O0 -g
	$(CC) uppg9.c -o uppg9 -Wall -O0 -g
	$(CC) uppg12.c -o uppg12 -Wall -O0 -g
	$(CC) uppg15.c uppg13.c -o uppg15 -Wall -O0 -g
	$(CC) uppg25.c -o uppg25 -Wall -O0 -g
	$(CC) uppg30.c uppg33.c binary_tree.c -o uppg30 -Wall -O0 -g
	$(CC) uppg31.c uppg33.c binary_tree.c -o uppg31 -Wall -O0 -g
	$(CC) uppg32.c uppg33.c binary_tree.c -o uppg32 -Wall -O0 -g

clean:
	rm -f uppg1
	rm -f uppg2
	rm -f uppg9
	rm -f uppg12
	rm -f uppg15
	rm -f uppg25
	rm -f uppg30
	rm -f uppg31
	rm -f uppg32
