default:
	$(CC) uppg4.c -o uppg4 -lm
	$(CC) uppg7.c -o uppg7 
	$(CC) uppg5.c -o uppg5 -lm
	$(CC) uppg10.c -o uppg10
	$(CC) uppg9.c -o uppg9

clean:
	rm -f uppg7
	rm -f uppg4
	rm -f uppg5
	rm -f uppg10
	rm -f uppg9
