default:
	$(CC) uppg1.c graph.c -o uppg1 -Wall -O0 -g
	$(CC) uppg2.c graph.c -o uppg2 -Wall -O0 -g
	$(CC) uppg4.c graph.c -o uppg4 -Wall -O0 -g
	$(CC) uppg7.c graph.c -o uppg7 -Wall -O0 -g

clean:
	rm -f uppg1
	rm -f uppg2
	rm -f uppg4
	rm -f uppg7
