CFLAGS += -Wall -O3

default:
	$(CC) $(CFLAGS) uppg7.c -o uppg7
	$(CC) $(CFLAGS) uppg15.c -o uppg15
	$(CC) $(CFLAGS) uppg8.c -o uppg8
	$(CC) $(CFLAGS) uppg2.c -o uppg2
	$(CC) $(CFLAGS) uppg1.c -o uppg1

clean:
	rm -f uppg7
	rm -f uppg15
	rm -f uppg8
	rm -f uppg2
	rm -f uppg1
