CFLAGS += -Wall -O3

default:
	$(CC) $(CFLAGS) uppg6.c -o uppg6 -lm
	$(CC) $(CFLAGS) uppg7.c -o uppg7
	$(CC) $(CFLAGS) uppg1.c -o uppg1
	$(CC) $(CFLAGS) uppg10.c -o uppg10

clean:
	rm -f uppg6
	rm -f uppg7
	rm -f uppg1
	rm -f uppg10
	rm -f *.txt
